spring.datasource.url=mysql://root:RbfbWJhleclEbiarHubKuwtuufsNNwIR@turntable.proxy.rlwy.net:12270/railway
spring.datasource.username=root
spring.datasource.password=RbfbWJhleclEbiarHubKuwtuufsNNwIR

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}
